query { user(login: "scottvr") { contributionsCollection { commitContributionsByRepository(maxRepositories: 100) { repository { nameWithOwner } } issueContributionsByRepository(maxRepositories: 100) { repository { nameWithOwner } } pullRequestReviewContributionsByRepository(maxRepositories: 100) { repository { nameWithOwner } } pullRequestContributionsByRepository(maxRepositories: 100) { repository { nameWithOwner } } } } }
